import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { padding: 20, backgroundColor: '#f5f7fa', flexGrow: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20 },
  title: { fontSize: 18, fontWeight: '600', color: '#1e293b', textAlign: 'center', marginBottom: 24 },
  scanBtn: { backgroundColor: '#2563eb', padding: 18, borderRadius: 12, alignItems: 'center', marginBottom: 12 },
  scanBtnText: { color: 'white', fontSize: 17, fontWeight: 'bold' },
  secondaryBtn: { backgroundColor: 'white', padding: 16, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: '#cbd5e1' },
  secondaryBtnText: { color: '#1e293b', fontSize: 16, fontWeight: '600' },
  divider: { textAlign: 'center', color: '#94a3b8', marginVertical: 20, fontSize: 13 },
  input: { backgroundColor: 'white', padding: 14, borderRadius: 10, borderWidth: 1, borderColor: '#cbd5e1', fontSize: 15, marginBottom: 10 },
  btn: { backgroundColor: '#1e40af', padding: 14, borderRadius: 10, alignItems: 'center' },
  btnText: { color: 'white', fontSize: 15, fontWeight: '600' },
  permText: { fontSize: 16, marginBottom: 20, textAlign: 'center' },
  overlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    alignItems: 'center', justifyContent: 'center',
  },
  scanFrame: { width: 250, height: 250, borderWidth: 3, borderColor: '#10b981', borderRadius: 16 },
  scanHint: { color: 'white', fontSize: 16, marginTop: 20, backgroundColor: 'rgba(0,0,0,0.5)', padding: 10, borderRadius: 8 },
  cancelBtn: { position: 'absolute', bottom: 40, alignSelf: 'center', backgroundColor: 'rgba(0,0,0,0.6)', padding: 14, borderRadius: 10 },
  cancelText: { color: 'white', fontSize: 16, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: 'white', borderRadius: 16, padding: 20 },
  modalTitle: { fontSize: 14, color: '#64748b', marginBottom: 6 },
  modalUrl: { fontSize: 15, color: '#1e293b', backgroundColor: '#f1f5f9', padding: 10, borderRadius: 8, marginBottom: 16 },
  verdictBox: { padding: 20, borderRadius: 12, alignItems: 'center', marginBottom: 16 },
  verdictText: { fontSize: 24, fontWeight: 'bold' },
  verdictScore: { fontSize: 14, color: '#475569', marginTop: 6 },
  features: { marginBottom: 16 },
  featuresTitle: { fontWeight: 'bold', marginBottom: 6, color: '#1e293b' },
  featureItem: { fontSize: 13, color: '#334155', marginLeft: 8, marginBottom: 2 },
  errorText: { color: '#b91c1c', textAlign: 'center', marginVertical: 16 },
  closeBtn: { backgroundColor: '#e2e8f0', padding: 14, borderRadius: 10, alignItems: 'center' },
  closeBtnText: { color: '#1e293b', fontSize: 15, fontWeight: '600' },
});